pytransform3d/test/test_urdf.py
pytransform3d/urdf.py

Let load_urdf only search for joint and links at top level by setting recursive search in robot.findAll to False.
It solves the issue **UrdfException: Joint type is missing in joint 'joint1'** when e.g. transmissions for certain joints are defined in the URDF file:
<joint name="the_joint_name" type="revolute">
<parent link="parent_link"/>
<child link="child_link"/>
<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
<axis xyz="0 0 1"/>
<limit effort="1.0" lower="-1.0" upper="1.0" velocity="1.0"/>
<dynamics damping="0.0" friction="0.0"/>
</joint>
<transmission name="transmission_name">
<type>the_type</type>
<joint name="the_joint_name">
<hardwareInterface>the_hardware_interface
</joint>
<actuator name="the_actuator_name">
<mechanicalReduction>int</mechanicalReduction>
</actuator>
</transmission> …

Fix load_urdf for urdf files with defined transmissions etc.

---

pytransform3d/test/test_transform_manager.py
pytransform3d/test/test_transformations.py
pytransform3d/transform_manager.py
pytransform3d/transformations.py
pytransform3d/urdf.py
pytransform3d/visualizer.py

Fixes #71, #31 
* Adds option to turn checks in TransformManager off to make it faster
TODO
`   ncalls  tottime  percall  cumtime  percall filename:lineno(function)`
Notes
* Using a set as proposed in #31 does not give us speed advantage in the benchmarks that I did.
* Caching inverted transformations results in 20% increased speed, but this is not worth implementing a complicated caching procedure.
Examples
Visualization of ATLAS from [this repository](https://github.com/team-vigir/vigir_atlas_common)
Visualization of Nao from [bullet](https://github.com/bulletphysics/bullet3)

[MRG] Make transform manager faster

---

doc/Makefile
doc/source/_static/rotations.svg
doc/source/_static/screw_axis.svg
doc/source/_static/transformations.svg
doc/source/_templates/class_without_inherited.rst
doc/source/api.rst
doc/source/conf.py
doc/source/index.rst
doc/source/rotations.rst
doc/source/transformation_ambiguities.rst
doc/source/transformations.rst
examples/plot_screw.py
pytransform3d/__init__.py
pytransform3d/camera.py
pytransform3d/rotations.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transformations.py
pytransform3d/test/test_urdf.py
pytransform3d/transform_manager.py
pytransform3d/transformations.py
pytransform3d/urdf.py
pytransform3d/visualizer.py

* Adds functions `vector_projection` and `check_skew_symmetric_matrix`
* Adds screw parameters, screw axis, exponential coordinates of transformations, unit twist, and matrix logarithm as new representations for transformations
* Improves documentation of SE(3)
TODO

[MRG] Screws / exponential coordinates of 3D transformations

---

doc/source/api.rst
examples/plot_matrix_from_two_vectors.py
pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

Fixes #78 
* Adds functions `norm_matrix` and `matrix_from_two_vectors`

[MRG] Normalization of rotation matrices

---

pytransform3d/rotations.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transformations.py
pytransform3d/transformations.py

See #114 for a further description.
All instances of `np.float` are replaced with `np.float64`.

Fix DeprecationWarning for `numpy>=1.20`

---

pytransform3d/plot_utils/_plot_functions.py
pytransform3d/visualizer/_artists.py
pytransform3d/visualizer/_figure.py

This is a breaking change for the current development version. It is not a breaking change for 1.9.1 and previous releases because capsule visualizations were not included previously.

[MRG] Capsule pose defines center of line segment

---

pytransform3d/plot_utils/_artists.py
pytransform3d/test/test_plot_utils.py

The label indicator can look cluttered in certain views and for those not familiar with rgb conventions it may be confusing. I prefer the look of the axes without the indicator, so this PR attempts to make it a little cleaner. I did it through kwargs instead of explicit parameter to be minimally invasive.

add ability to hide label indicator

---

pytransform3d/plot_utils/_artists.py

Fix Arrow3D for matplotlib 3.5

---

doc/source/api.rst
pytransform3d/batch_rotations.py
pytransform3d/batch_rotations.pyi
pytransform3d/rotations/__init__.py
pytransform3d/rotations/_slerp.py
pytransform3d/rotations/_slerp.pyi
pytransform3d/test/test_batch_rotations.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_trajectories.py
pytransform3d/test/test_transformations.py
pytransform3d/trajectories.py
pytransform3d/trajectories.pyi

Fixes #122 
- Add `pytransform3d.rotations.pick_closest_quaternion`
- Add `pytransform3d.batch_rotations.smooth_quaternion_trajectory`
- Add `pytransform3d.trajectories.mirror_screw_axis_direction`
- Add optional parameter `shortest_path` to indicate that sign ambiguity should be resolved in `quaternion_slerp_batch`, `quaternion_slerp`, and `rotor_slerp`
- Document `slerp_weights` and correct type hints
TODO

[WIP] Solve ambiguities in interpolations

---

CONTRIBUTING.md
README.md
doc/source/index.rst
examples/animations/animate_rotation.py
examples/animations/animate_trajectory.py
examples/visualizations/vis_moving_basis.py
examples/visualizations/vis_moving_trajectory.py
manifest.xml
pytransform3d/__init__.py
pytransform3d/batch_rotations.py
pytransform3d/rotations/_conversions.py
pytransform3d/rotations/_testing.py
pytransform3d/test/test_rotations.py
setup.py

- Fix `pytransform3d.rotations.axis_angle_from_matrix` with floating point precision errors in input rotation matrix (#189)
- pytransform3d.rotations.matrix_from
- pytransform3d.rotations.matrix_from_angle
- pytransform3d.rotations.matrix_from_euler_xyz
- pytransform3d.rotations.matrix_from_euler_zyx
- pytransform3d.rotations.euler_xyz_from_matrix
- pytransform3d.rotations.euler_zyx_from_matrix
- pytransform3d.rotations.assert_euler_xyz_equal
- pytransform3d.rotations.assert_euler_zyx_equal
- pytransform3d.rotations.e_xyz_id
- pytransform3d.rotations.e_zyx_id
- Changed URL to https://github.com/dfki-ric/pytransform3d

Development branch, release 1.14.0

---

pytransform3d/batch_rotations.py
pytransform3d/test/test_batch_rotations.py

...in function smooth_quaternion_trajectory
Fix #187

Raise ValueError when no quaternion is given

---

pytransform3d/test/test_urdf.py
pytransform3d/urdf.py

hi @AlexanderFabisch , I appreciate your work on this package! I have been playing around with it and am now building a small development tool that uses this package. 
For my application it would be very helpful if fixed joints can also be identified based on their 'joint_name' and not only via their 'from_name' + 'to_name' combination. Please find attached a draft change. 
Note:
- I did not run the unit tests yet so it's very possible that the current suggestion causes integration issues
- I did not change _get_joint_limits_ since a fixed joint will also have these limits defined.
Curious to hear your thoughts. Perhaps there is a clear reason not to do this. In that case I will solve it locally in my code.

chore: draft change

---

.github/workflows/python-package.yml
pytransform3d/test/test_batch_rotations.py
pytransform3d/test/test_camera.py
pytransform3d/test/test_coordinates.py
pytransform3d/test/test_plot_utils.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transform_manager.py
pytransform3d/test/test_transformations.py
pytransform3d/test/test_urdf.py
pytransform3d/transformations/_testing.py
setup.py

Fixes #220 
TODO
```
ack nose pytransform3d
pytransform3d/test/test_transformations.py
33:from nose.tools import (assert_equal, assert_almost_equal,
pytransform3d/test/test_rotations.py
4:from nose.tools import (assert_almost_equal, assert_equal, assert_true,
```

Remove dependency on nose

---

pytransform3d/rotations/_utils.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transform_manager.py
pytransform3d/test/test_transformations.py

Fixes #218 
Numerical error of the determinant is (only a bit) larger than the error in individual components of the rotation matrix multiplied with its transpose.
```python
def test_rotation_matrix_precision_error():
R = pr.active_matrix_from_extrinsic_roll_pitch_yaw([0.5, 0.5, 0.5])
for _ in range(40):
R = R.dot(R)
det_error = abs(1.0 - np.linalg.det(R))
RRT_error = np.max(R.dot(R.T) - np.eye(3))
assert RRT_error <= det_error
```
Hence, we don't have to check whether det(R) is 1. We just have to check for reflection.

[WIP] Fix check of det of rotation matrix

---

pytransform3d/camera.py

Adds missing strict_check argument. (see #54)
Fixes problem that occurs when plotting cameras. cam2world will be checked in line 266 and inside of transform in line 278. For transform the strickt_check argument was missing.

Adds missing strict_check argument in camera.py

---

pytransform3d/rotations/_conversions.py
pytransform3d/test/test_rotations.py

There's a slight edge case I found due to numerical instability where the matrix conversion will error for arccosine if the value is 1.0 + epsilon and provide a NaN value. It will trigger specifically the code path in lines 995-996 but I have not found an orientation that triggers 997-998. If you want, I can remove that code path or add a corresponding test.

Fix and test edge case for matrix conversion

---

pytransform3d/geometry.py
pytransform3d/geometry.pyi
pytransform3d/plot_utils/_plot_functions.py
pytransform3d/plot_utils/_plot_functions.pyi
pytransform3d/test/test_geometry.py
pytransform3d/uncertainty.py

[WIP] Refactor geometry

---

doc/source/api.rst
doc/source/rotations.rst
examples/plots/plot_dual_quaternion_interpolation.py
pytransform3d/rotations/_jacobians.py
pytransform3d/rotations/_quaternion_operations.py
pytransform3d/rotations/_rotors.py
pytransform3d/rotations/_slerp.py
pytransform3d/rotations/_utils.py
pytransform3d/test/test_transformations.py
pytransform3d/trajectories.py
pytransform3d/transformations/__init__.py
pytransform3d/transformations/_conversions.py
pytransform3d/transformations/_dual_quaternion_operations.py
pytransform3d/transformations/_jacobians.py
pytransform3d/transformations/_pq_operations.py
pytransform3d/transformations/_pq_operations.pyi
pytransform3d/transformations/_transform_operations.py
pytransform3d/uncertainty.py

Fixes #273 
* Add `pytransform3d.transformations.pq_slerp`, which performs linear interpolation of position and SLERP of quaternion.
* Add connections between docstrings through "See Also" sections.

SLERP for position + quaternion

---

doc/source/api.rst
doc/source/user_guide/rotations.rst
pytransform3d/rotations/__init__.py
pytransform3d/rotations/_mrp.py
pytransform3d/rotations/_mrp.pyi
pytransform3d/rotations/_quaternion_operations.py
pytransform3d/test/test_rotations.py

Concatenate MRPs

---

README.md
doc/source/install.rst

Zsh users (or MacOS users, which have [Zsh](https://www.zsh.org/) as default from 2020) will encounter problems following the README, e.g.:
```
(.venv) kopytjuk in ~/Code/example-project ● λ pip install pytransform3d[all]
zsh: no matches found: pytransform3d[all]
```
The reason for this, that Zsh uses `[]` for some string generation, see SO answer [here](https://apple.stackexchange.com/a/427617).
This PR fixes is, by wrapping the command in quotes. It works on both `bash` and `zsh`.

Update `pip install` installation instructions to work on Zsh

---

.github/workflows/python-package.yml

Python 3.12 and 3.13 are released and should be tested in GHA as well:

Add Python releases 3.12 and 3.13 to CI 

---

.github/workflows/python-package.yml
doc/source/api.rst
pytransform3d/test/test_transformations.py
pytransform3d/transformations/__init__.py
pytransform3d/transformations/_dual_quaternion_operations.py
pytransform3d/transformations/_dual_quaternion_operations.pyi
pytransform3d/transformations/_testing.py
pytransform3d/transformations/_utils.py

- Add `transformations.norm_dual_quaternion`
- Add option `unit` to `transformations.concatenate_dual_quaternions` to allow multiplication of unnormalized dual quaternions
- Update `transformations.dual_quaternion_requires_renormalization` to check for orthogonality of real and dual quaternion

Normalization of dual quaternions

---

doc/source/api.rst
examples/plots/plot_polar_decomposition.py
pytransform3d/rotations/__init__.py
pytransform3d/rotations/_polar_decomp.py
pytransform3d/rotations/_polar_decomp.pyi
pytransform3d/rotations/_utils.py
pytransform3d/test/test_rotations.py

* Add orthonormalization by polar decomposition
TODO

ENH: Orthonormalization with polar decomposition

---

pytransform3d/test/test_urdf.py
pytransform3d/urdf.py

The current parser does not properly handle URDF files which contain an `xmlns` (XML namespace) attribute. This is largely to do with the underlying XML parser which successfully parses the tree but prepends the tag/name for all elements (incl root) with `{namespace}`. This breaks the assumptions made about the root tag and causes the parser to raise an exception.
Additionally, further nodes will not parse correctly with this namespace tag.
To resolve this:
1. Add a normalization step which traverses the graph and strips the namespace prefix from all elements
2. Adds a test with an example XML string.
It was surprising to me that the parser fails when it is particularly common to see URDF files with a namespace (most commonly from ROS). I am not sure of a better/cleaner way, but a simple …

Fix for URDF parsing with XML namespace
