pytransform/transformations.py

Improve documentation of position and quaternion

---

doc/source/animations.rst
doc/source/api.rst
doc/source/index.rst
examples/animate_rotation.py
examples/animate_trajectory.py
pytransform/plot_utils.py
pytransform/rotations.py
pytransform/trajectories.py
pytransform/transformations.py

Fixes #9 
Adds animation feature for transformations and trajectories.
Generated from `examples/animate_trajectory.py` with
```python
anim.save("trajectory.gif", dpi=80, writer="imagemagick")
```

Animations

---

pytransform3d/test/test_transform_manager.py
pytransform3d/transform_manager.py

Debug functions for TransformManager

---

pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

Based on suggestion from @mojodo

Numerical stable axis_angle_from_matrix()

---

pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

Fix SLERP between same rotations

---

pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

Numericaly stable angle between vectors

---

pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

Increase tolerance for inversion test of rotation matrices

---

pytransform3d/rotations.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transform_manager.py
pytransform3d/test/test_transformations.py
pytransform3d/transform_manager.py
pytransform3d/transformations.py

Option to deactivate strict checks of rotation matrices

---

pytransform3d/rotations.py

[MRG] Document convention of axis-angle

---

.circleci/config.yml
doc/source/api.rst
doc/source/rotations.rst
doc/source/transformation_ambiguities.rst
examples/animate_quaternion_integration.py
examples/animate_quaternion_interpolation.py
examples/plot_quaternion_integrate.py
pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

* introduces *compact axis-angle* as a new concept to represent orientations and adds conversions from and to axis-angle, quaternion, and rotation matrix
* uses compact axis-angle to represent angular velocities
* adds function to compute time derivatives of a quaternion sequence
* adds function to integrate angular velocities to a sequence of quaternions
TODO

[MRG] Quaternion gradient and integration

---

doc/source/api.rst
examples/plot_cylinder.py
examples/plot_rotate_cylinder.py
pytransform3d/plot_utils.py

[MRG] Improve plot_utils for better illustrations

---

doc/source/api.rst
pytransform3d/test/test_transformations.py
pytransform3d/transformations.py

* Adds vector_to_direction, vectors_to_directions, and vectors_to_points

[MRG] vector_to_direction

---

doc/source/api.rst
examples/render_urdf.py
pytransform3d/__init__.py
pytransform3d/test/test_transformations.py
pytransform3d/transformations.py

[WIP] Better rendering

---

doc/source/api.rst
examples/plot_axis_angle_from_two_vectors.py
pytransform3d/rotations.py
pytransform3d/test/test_rotations.py

[MRG] Add axis-angle from two vectors

---

pytransform3d/test/test_urdf.py
pytransform3d/urdf.py
pytransform3d/visualizer.py

Fixes #51
* Adds support for prismatic and continuous URDF joints
TODO

Support for more URDF joints

---

pytransform3d/rotations.py
pytransform3d/test/test_urdf.py
pytransform3d/urdf.py
pytransform3d/visualizer.py
test/test_data/simple_mechanism.urdf

[MRG] Feature/urdf material tag

---

doc/source/api.rst
examples/vis_cylinder.py
examples/vis_cylinder_with_wrench.py
examples/vis_ee_wrench.py
examples/vis_moving_robot.py
pytransform3d/test/test_transformations.py
pytransform3d/transformations.py
test/test_data/robot_with_visuals.urdf

* Adds function `adjoint_from_transformation`

[MRG] Examples with wrenches

---

doc/source/transform_manager.rst
pytransform3d/test/test_transform_manager.py
pytransform3d/transform_manager.py

Fixes #81 
* Adds method `TransformManager.remove_transform`

[MRG] Remove transform

---

README.md
doc/source/_static/rotations.svg
doc/source/_static/transformations.svg
doc/source/api.rst
doc/source/conf.py
doc/source/euler_angles.rst
doc/source/index.rst
doc/source/rotations.rst
doc/source/transformation_ambiguities.rst
examples/apps/app_transformation_editor.py
examples/plots/plot_camera.py
examples/plots/plot_compare_rotations.py
examples/plots/plot_euler_angles.py
examples/plots/plot_transform_manager.py
pytransform3d/editor.py
pytransform3d/rotations.py
pytransform3d/test/test_camera.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transform_manager.py

[MRG] Implement more euler angle conventions

---

pytransform3d/test/test_urdf.py
pytransform3d/urdf.py

- Adds option to convert 'package://' in URDF files to a specified directory

[MRG] Allow to set 'package_dir' for URDFs

---

.circleci/config.yml
examples/plots/plot_robot.py
pytransform3d/plot_utils.py
pytransform3d/urdf.py

Fixes #92 
* Adds options to control appearance of collision objects and visuals in plots: wireframe, convex hull, alpha value

[MRG] Feature/control mesh plot

---

pytransform3d/visualizer.py

* Fixes visualization of TransformManager

[MRG] Don't access attributes that don't exist

---

README.md
doc/source/api.rst
doc/source/euler_angles.rst
doc/source/rotations.rst
doc/source/transformation_ambiguities.rst
doc/source/transformations.rst
examples/README.rst
examples/plots/plot_pose_trajectory.py
examples/plots/plot_straight_line_path.py
pytransform3d/__init__.py
pytransform3d/batch_rotations.py
pytransform3d/rotations.py
pytransform3d/test/test_batch_rotations.py
pytransform3d/test/test_trajectories.py
pytransform3d/test/test_transformations.py
pytransform3d/trajectories.py
pytransform3d/transformations.py

* Adds batch conversions of orientation and pose representations and similar operations
* Adds function `norm_exponential_coordinates`
TODO

[MRG] Batch operations on rotations

---

pytransform3d/plot_utils.py

[MRG] More useful warning for missing mesh filename

---

pytransform3d/test/test_urdf.py
pytransform3d/urdf.py

[MRG] Make collision object and visual frames unique

---

doc/source/api.rst
doc/source/transformations.rst
pytransform3d/batch_rotations.py
pytransform3d/test/test_batch_rotations.py
pytransform3d/test/test_trajectories.py
pytransform3d/test/test_transformations.py
pytransform3d/trajectories.py
pytransform3d/transformations.py

[MRG] Batch operations for dual quaternions

---

doc/source/api.rst
pytransform3d/test/test_trajectories.py
pytransform3d/trajectories.py
pytransform3d/trajectories.pyi

[MRG] Invert batch of transforms

---

pytransform3d/test/test_transform_manager.py
pytransform3d/transform_manager.py
pytransform3d/transform_manager.pyi
pytransform3d/urdf.py
pytransform3d/urdf.pyi

- Frame names can be any hashable
- Add type hints for attributes of URDF geometries

[MRG] Extend typehints

---

doc/source/api.rst
examples/plots/plot_random_geometries.py
examples/visualizations/vis_capsule.py
examples/visualizations/vis_cone.py
pytransform3d/__init__.py
pytransform3d/plot_utils/__init__.py
pytransform3d/plot_utils/_plot_functions.py
pytransform3d/plot_utils/_plot_functions.pyi
pytransform3d/test/test_plot_utils.py
pytransform3d/visualizer/__init__.py
pytransform3d/visualizer/_artists.py
pytransform3d/visualizer/_artists.pyi
pytransform3d/visualizer/_figure.py
pytransform3d/visualizer/_figure.pyi

* Adds `plot_ellipsoid`, `plot_capsule`, and `plot_cone` to `pytransform3d.plot_utils`
* Adds visualization of capsule and cone

[MRG] Feature/geometries

---

doc/source/api.rst
pytransform3d/rotations/__init__.py
pytransform3d/rotations/_utils.py
pytransform3d/rotations/_utils.pyi
pytransform3d/test/test_rotations.py

* Adds `pytransform3d.rotations.plane_basis_from_normal`

[MRG] Compute plane basis from normal

---

doc/source/api.rst
examples/plots/plot_spherical_grid.py
pytransform3d/coordinates.py
pytransform3d/coordinates.pyi
pytransform3d/test/test_coordinates.py

[MRG] Conversions between coordinate systems

---

doc/source/api.rst
pytransform3d/test/test_trajectories.py
pytransform3d/trajectories.py
pytransform3d/trajectories.pyi

* Adds `trajectories.concat_one_to_many` to apply one transformation to multiple others
TODO

[MRG] Batch concatenation of transformations

---

doc/source/api.rst
examples/visualizations/vis_scatter.py
pytransform3d/visualizer/__init__.py
pytransform3d/visualizer/_artists.py
pytransform3d/visualizer/_artists.pyi
pytransform3d/visualizer/_figure.py
pytransform3d/visualizer/_figure.pyi

Adds function `Figure.scatter` and artist `PointCollection3D` to Open3D-based visualizer

Scatter plot for Open3D

---

doc/source/transformations.rst

Fixes #175
Docs enhancement from #175. I can change this to target develop if you prefer. I also realize its a small update so you may wait to batch up other changes before updating the documentation site.

Clarify the descriptions of SE3 in docs

---

README.md
doc/source/transformations.rst
pytransform3d/__init__.py
pytransform3d/camera.py
pytransform3d/editor.py
pytransform3d/plot_utils/_artists.py
pytransform3d/plot_utils/_plot_functions.py
pytransform3d/rotations/_plot.py
pytransform3d/rotations/_rotors.py
pytransform3d/rotations/_slerp.py
pytransform3d/rotations/_utils.py
pytransform3d/test/test_plot_utils.py
pytransform3d/transform_manager.py
pytransform3d/transformations/_conversions.py
pytransform3d/transformations/_transform_operations.py
pytransform3d/transformations/_utils.py

* Add option `draw_label_indicator` to `Frame` artist class for Matplotlib
* Make Arrow3D compatible to matplotlib 3.5
* Describe SE(3) more clearly.

Development branch, release 1.12.0

---

pytransform3d/rotations/_conversions.py
pytransform3d/test/test_rotations.py

Fix issue #198

---

LICENSE
doc/source/camera.rst
doc/source/conf.py
pytransform3d/__init__.py
pytransform3d/plot_utils/_artists.py
pytransform3d/test/test_urdf.py
pytransform3d/urdf.py
pytransform3d/visualizer/_artists.py

* UrdfTransformManager also stores fixed joints internally #203
* Use numpy.int64 instead of numpy.int

Development branch, release 2.1.0

---

pytransform3d/plot_utils/_plot_functions.py

Fix bug in plot_cylinder (#206)

---

examples/plots/plot_quaternion_integrate.py
examples/plots/plot_quaternion_slerp.py
examples/plots/plot_sample_rotations.py
pytransform3d/rotations/_utils.py

And some minor corrections of the documentation.

Compare random rotations

---

examples/plots/plot_spheres.py
pytransform3d/plot_utils/__init__.py
pytransform3d/plot_utils/_plot_functions.py
pytransform3d/plot_utils/_plot_functions.pyi

plot_sphere can also be called with multiple centers, so the sin cos meshgrid does not have to be recomputed.

Plot multiple spheres

---

doc/source/api.rst
examples/visualizations/vis_probabilistic_robot_kinematics.py
pytransform3d/test/test_uncertainty.py
pytransform3d/uncertainty.py
pytransform3d/uncertainty.pyi

Fixes #238 
TODO
- Concatenation of locally uncertain transformations

Probabilistic robot kinematics

---

CITATION.cff
examples/visualizations/vis_probabilistic_robot_kinematics.py
pytransform3d/__init__.py
pytransform3d/rotations/_conversions.py
pytransform3d/rotations/_quaternion_operations.py
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transform_manager.py
pytransform3d/transform_manager.py
pytransform3d/transformations/_dual_quaternion_operations.py

* Fix edge cases of euler angle computation from rotation matrix
* Fix inconsistency when removing transforms from the `TransformManager`
* Add citation file (CITATION.cff) to repository

Development branch, release 3.2.0

---

pytransform3d/_mesh_loader.py

Fixes #284 
Tested with the following versions of trimesh:
* trimesh==3.9.35
* trimesh==4.0.0rc1
* trimesh==4.1
* trimesh==4.2
* trimesh==4.4
* trimesh==4.4.8
* trimesh==4.4.9

[MRG] Fix loading collada scene with trimesh v4

---

doc/source/user_guide/rotations.rst

fix the physical meaning of column vector in rotation matrix

Update rotations.rst to fix the meaning of column vector in rotation matrix

---

.github/workflows/python-package.yml
doc/source/user_guide/rotations.rst
pytransform3d/__init__.py

* Fix interpretation of rotation matrix (see #321)
* Add Python versions 3.12 and 3.13 to CI

Development branch, release 3.10.1

---

doc/source/api.rst
pytransform3d/uncertainty.py
pytransform3d/uncertainty.pyi

Should be merged together with #282

Refactor: Extract Frechet mean

---

pytransform3d/_mesh_loader.py

Fix #308 
trimesh does not support loading color information from STL files as pointed out in https://github.com/mikedh/trimesh/issues/1819

[MRG] Load mesh colors correctly

---

doc/source/api.rst
doc/source/user_guide/rotations.rst
doc/source/user_guide/transformations.rst
examples/plots/plot_dual_quaternion_interpolation.py
pytransform3d/rotations/__init__.py
pytransform3d/rotations/_slerp.py
pytransform3d/rotations/_slerp.pyi
pytransform3d/test/test_rotations.py
pytransform3d/test/test_transformations.py
pytransform3d/transformations/__init__.py
pytransform3d/transformations/_dual_quaternion_operations.py
pytransform3d/transformations/_transform_operations.py
pytransform3d/transformations/_transform_operations.pyi

- Add ScLERP for transformation matrices
- Add SLERP for rotation matrices

Additional interpolation features
